import tailwindAnimate from "tailwindcss-animate";
const config = {
    darkMode: ["class"],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{ts,tsx}',
    ],
    
    prefix: "",
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                "inverse-surface": "#0b0f10",
                "secondary-fixed": "#ffc1d6",
                "primary-fixed": "#b28cff",
                "on-tertiary-fixed": "#37001d",
                "on-secondary-fixed": "#6b003e",
                "surface-tint": "#702ae1",
                "primary": "#702ae1",
                "secondary": "#b00d6a",
                "error": "#b41340",
                "on-secondary": "#ffeff2",
                "tertiary-fixed": "#fd8eba",
                "tertiary-container": "#fd8eba",
                "on-secondary-fixed-variant": "#9e005e",
                "error-dim": "#a70138",
                "surface-bright": "#f5f7f9",
                "on-secondary-container": "#8e0054",
                "outline": "#747779",
                "on-error-container": "#510017",
                "on-error": "#ffefef",
                "surface-container-highest": "#d9dde0",
                "primary-container": "#b28cff",
                "on-background": "#2c2f31",
                "on-tertiary-fixed-variant": "#6b1741",
                "on-surface-variant": "#595c5e",
                "tertiary-dim": "#882f57",
                "surface-container-low": "#eef1f3",
                "on-primary-fixed": "#000000",
                "surface-dim": "#d0d5d8",
                "primary-dim": "#6411d5",
                "outline-variant": "#abadaf",
                "secondary-dim": "#9d005d",
                "tertiary-fixed-dim": "#ed81ac",
                "error-container": "#f74b6d",
                "background": "#f5f7f9",
                "tertiary": "#963b64",
                "secondary-fixed-dim": "#ffaccb",
                "surface": "#f5f7f9",
                "on-primary": "#f8f0ff",
                "inverse-on-surface": "#9a9d9f",
                "secondary-container": "#ffc1d6",
                "on-surface": "#2c2f31",
                "surface-container": "#e5e9eb",
                "on-tertiary-container": "#5f0c38",
                "surface-container-lowest": "#ffffff",
                "surface-container-high": "#dfe3e6",
                "on-primary-fixed-variant": "#390083",
                "on-tertiary": "#ffeff2",
                "primary-fixed-dim": "#a67aff",
                "on-primary-container": "#2e006c",
                "inverse-primary": "#a476ff",
                "surface-variant": "#d9dde0",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                foreground: "hsl(var(--foreground))",
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            keyframes: {
                "accordion-down": {
                    from: { height: "0" },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: "0" },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
        },
    },
    plugins: [tailwindAnimate],
};
export default config;
